Feature/transaction detail
Pjotrrrr/android-study pull request #2
Opened 2023-07-25 11:33 UTC by Pjotrrrr

2023-07-25 11:43 UTC, android-angie commented on .idea/kotlinc.xml
this file should be added to .gitignore

2023-07-25 11:47 UTC, android-angie commented on app/src/main/java/com/example/recyclerviewtest/adapters/BindingAdapters.kt
> +            }
we should also have 'else' branch here. If we don't provide the info what happens on else, next time the same view calls this method, it will stay bold even if the parameter is false, since the method doesn't know how to handle false.

2023-07-25 11:50 UTC, android-angie commented on app/src/main/java/com/example/recyclerviewtest/adapters/TagsAdapter.kt
> +            deleteTag(position)
instead of 'position', we should use holder.adapterPosition here. RecyclerViewAdapter only guarantees that position will be the same in the moment when onBindViewHolder is called. But if the clicklistener is executed after, there's no guarantee the position will be the one that you are expecting, so it can lead the app to crash or to execute a listener over wrong item 😄 holder.adapterPosition fetches the most recent position and it will always be the one you need 😄

2023-07-25 11:52 UTC, android-angie commented on app/src/main/java/com/example/recyclerviewtest/adapters/TransactionAdapter.kt
> +                    itemView.findNavController().navigate(CashDeskFragmentDirections.actionCashDeskFragmentToTransactionDetailFragment(binding.transaction!!))
we should avoid !! operators. That operator forces non nullability, which means that if somehow happens that item is null, the app will crash. Instead, we should do a null check using ? operator

2023-07-25 11:53 UTC, android-angie commented on app/src/main/java/com/example/recyclerviewtest/adapters/TransactionDetailAdapter.kt
> +        return TransactionInfoFragment(this.transaction)
this is fine for now, but in the next batch we'll replace this argument with viewmodel implementation 😄

2023-07-25 11:54 UTC, android-angie commented on app/src/main/java/com/example/recyclerviewtest/adapters/TransactionInfoAdapter.kt
> +class TransactionInfoAdapter(fragmentManager: FragmentManager,
Since this adapter is used for binding quests, we should rename it to something more descriptive

2023-07-25 11:57 UTC, android-angie commented on app/src/main/java/com/example/recyclerviewtest/fragments/QuestBoxFragment.kt
> +}
viewpager can also be used with regular recycler adapter, so this whole class can become just a viewholder, instead of fragment :) This will also change your TransactionInfoAdapter

2023-07-25 12:03 UTC, android-angie commented on app/src/main/res/layout/list_item.xml
this item should also be renamed to something more descriptive

2023-07-25 12:04 UTC, android-angie commented on app/src/main/res/layout/tags_item.xml
items should be named with item prefix (item_tags)

2023-07-25 12:06 UTC, android-angie commented on app/src/main/java/com/example/recyclerviewtest/adapters/TransactionAdapter.kt
> +                    itemView.findNavController().navigate(CashDeskFragmentDirections.actionCashDeskFragmentToTransactionDetailFragment(binding.transaction!!))
navigation should not be handled directly from adapter. Adapter should be as 'stupid' as possible, and only handle inflating views and binding data. You should invoke some kind of callback when click happens, and handle the navigation in fragment 😄

2023-07-25 12:15 UTC, android-angie commented on app/src/main/java/com/example/recyclerviewtest/MainActivity.kt
>      }
i don't think you need this at all 😄 the hardware back is handled by the system, and if in any fragment you have the need to navigate back without using the hardware back, you can (and should) use fragment's navcontroller, that can be fetched by calling findNavController method 😄

2023-07-25 12:15 UTC, android-angie requested changes
Minor polishing needed

2023-07-26 10:40 UTC, android-angie commented on .idea/.gitignore
gitignore file should also exist in app folder. You can find android gitignore file online 😄

2023-07-26 10:47 UTC, android-angie commented on app/src/main/java/com/example/recyclerviewtest/fragments/CashDeskFragment.kt
> +        }
maybe this part is messing with your transitions. Since this is a fragment, you don't need view's navcontroller, you can just use fragment's 😄 In that case, you will have just findNavController, without the view

2023-07-26 10:47 UTC, android-angie commented on app/src/main/java/com/example/recyclerviewtest/fragments/CashDeskFragment.kt
> +        transaction.let {
if your callback only accepts non nullable transactions, then this let block doesn't make sense and it can be removed 😄

2023-07-26 10:50 UTC, Pjotrrrr commented on app/src/main/java/com/example/recyclerviewtest/fragments/CashDeskFragment.kt
> +        }
Originally I had it the way you are suggesting, this was just one of many attempts to fix it. :D It keeps doing the same unfortunately.

2023-07-26 12:51 UTC, android-angie approved these changes

2023-07-26 12:52 UTC, merged